<?php

namespace AppBundle\Repository;

/**
 * AfeccioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfeccioneRepository extends \Doctrine\ORM\EntityRepository
{
}
