<?php

namespace AppBundle\Repository;

/**
 * CampaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaniaRepository extends \Doctrine\ORM\EntityRepository
{
}
