<?php

namespace AppBundle\Repository;

/**
 * ConstanciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstanciaRepository extends \Doctrine\ORM\EntityRepository
{
}
