<?php

namespace AppBundle\Repository;

/**
 * DienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DienteRepository extends \Doctrine\ORM\EntityRepository
{
}
