<?php

namespace AppBundle\Repository;

/**
 * EntericaGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntericaGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
