<?php

namespace AppBundle\Repository;

/**
 * EntericaCapituloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntericaCapituloRepository extends \Doctrine\ORM\EntityRepository
{
}
