<?php

namespace AppBundle\Repository;

/**
 * EntericaElementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntericaElementoRepository extends \Doctrine\ORM\EntityRepository
{
}
