<?php

namespace AppBundle\Repository;

/**
 * EvolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolucionRepository extends \Doctrine\ORM\EntityRepository
{
}
