<?php

namespace AppBundle\Repository;

/**
 * HistoriaOdontologicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaOdontologicaRepository extends \Doctrine\ORM\EntityRepository
{
}
