<?php

namespace AppBundle\Repository;

/**
 * ImagenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenesRepository extends \Doctrine\ORM\EntityRepository
{
}
