<?php

namespace AppBundle\Repository;

/**
 * ObservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionRepository extends \Doctrine\ORM\EntityRepository
{
}
