<?php

namespace AppBundle\Repository;

/**
 * OdontogramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OdontogramaRepository extends \Doctrine\ORM\EntityRepository
{
}
