<?php

namespace AppBundle\Repository;

/**
 * RecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetaRepository extends \Doctrine\ORM\EntityRepository
{
}
