<?php

namespace AppBundle\Repository;

/**
 * ReposoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReposoRepository extends \Doctrine\ORM\EntityRepository
{
}
