<?php

namespace AppBundle\Repository;

/**
 * ServicioProfesionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioProfesionalRepository extends \Doctrine\ORM\EntityRepository
{
}
