<?php

namespace AppBundle\Repository;

/**
 * TratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TratamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
